### ISSUE TITLE
zenbu.py issue

### ISSUE THREAD

**Issue by xable** [metakirby5/sanpai#9]
Package installed from AUR [zenbu-git](https://aur.archlinux.org/packages/zenbu-git)
```
python --version
Python 3.10.2
```
After run zenbu in the terminal got these error's:
```
Traceback (most recent call last):
  File "/usr/bin/zenbu", line 33, in <module>
    sys.exit(load_entry_point('zenbu==1.0.5', 'console_scripts', 'zenbu')())
  File "/usr/lib/python3.10/site-packages/zenbu.py", line 770, in main
    zenbu = Zenbu(
  File "/usr/lib/python3.10/site-packages/zenbu.py", line 328, in __init__
    self.refresh()
  File "/usr/lib/python3.10/site-packages/zenbu.py", line 343, in refresh
    deep_update_dict(
  File "/usr/lib/python3.10/site-packages/zenbu.py", line 171, in deep_update_dict
    if isinstance(d, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```
And no more. Run with any functional flags e.g. -l, w --dry prints same error. Zenbu only appears correctly w/o any errors with help flags (-h).

**Comment by metakirby5** [comment]
Should be fixed now, can you give it a try?

**Comment by xable** [comment]
Fixed! Thanks!
Zenbu the best utility, long live! 😉
